server:
  port: 2001
#
eureka:
  instance:
    hostname: eureka2001 # Eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己就是服务端，职责就是维护服务实例，并不需要去检索服务
    service-url: # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka2002:2002/eureka/,http://eureka2003:2003/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护机制，保证不可用服务被及时剔除
    eviction-interval-timer-in-ms: 2000 #

#--spring.profiles.active=eureka8764