server:
  port: 3001
spring:
  application:
    name: metoo-user-service # 注册到服务中心名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver #com.mysql.jdbc.Driver MySQL驱动包
    url: jdbc:mysql://localhost:3306/metoo_tv5?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-spirng: 192.168.31.66:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities #所有Entity别名类所在包


# Eureka 注册中心(停更)
#  client:
#    register-with-eureka: true # 表示是否注册到EurekaServer默认为True
#    fetch-registry: true # 是否从EurekaServer抓取已有的注册信息，默认为True,单节点无所谓，集群必须设置为True才能配合Ribbon使用负载均衡
#    service-url:
#      defaultZone: http://eureka2001:2001/eureka/,http://eureka2002:2002/eureka/,http://eureka2003:2003/eureka/
#  instance:
#    instance-id: USER-SERVICE-ONE
#    prefer-ip-address: true # 访问路径可以显示IP地址
#    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
#    lease-expiration-duration-in-seconds: 2 # Eureka 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务

# Zookeeper
#spring:
#  cloud:
#    zookeeper:
#      connect-spirng: 192.168.31.66:2181